spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      routes:
        - id: news-service
          uri: lb://news-service
          predicates:
            - Path=/v1/news/**
        - id: comment-service
          uri: lb://comment-service
          predicates:
            - Path=/v1/comment/**
      discovery:
        locator:
          enabled: true
server:
  port: 8888

eureka:
  client:
    register-with-eureka: true
    service-url:
      defaultZone: ${EUREKA_URI}
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${random.value}